blank_issues_enabled: true
contact_links:
  - name: Ask A Question
    url: https://github.com/brucebentley/SlackCleaner/discussions/new
    about: Ask & discuss questions with other community members.
